name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Open Sans C
    fonts:
      - asset: fonts/OpenSansCondensed-Light.ttf
      - asset: fonts/OpenSansCondensed-Bold.ttf

  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat-Regular.ttf
